### ISSUE TITLE
question: inconsistent payload returning from search.query

### ISSUE THREAD

**Issue by montrealist** [box/box-node-sdk#107]
We're experiencing cases with payload returning from `search.query` [endpoint](https://docs.box.com/reference#searching-for-content) looking like this (`total_count` is not zero but the `entries` array is empty):

```
{
    total_count: 10,
    entries:
        [],
    limit: 1,
    offset: 0
}
```

90% of the time we receive this:

```
{
    total_count: 1,
    entries:
        [
            {
                type: 'file',
                id: '126793694652',
                // rest of the payload
            }
        ],
    limit: 1,
    offset: 0
}
```

Our use case: a script hits a Box folder programmatically and uploads a CSV file to it (filename is always the same). Before uploading, it performs a search to check whether a file with that name already exists; if it does - we upload a new version. If it does not - we upload a new file. This action may sometimes repeatedly run within the span of 10 minutes.

Could this be somehow related to the below note in the documentation?

> If an item is added to Box then it becomes accessible through the search endpoint after ten minutes.

**Comment by mattwiller** [comment]
@montrealist Under some circumstances, like if you no longer have access to some items in the search results, the entries displayed may not match up with the `total_count`.

However, I think that you might be able to work around this problem; search is probably not the most efficient way to do what you're trying to do.  Rather than looking through your entire Box account for a file with the same name, could you just get the names of all files in the folder and check if one with the same name is there?

```js
var targetName = 'whatever the file name is';
client.folders.getItems(folderID, {limit: 1000, fields:'name'}, function(err, items) {

    if (err) {
        // handle error
        return;
    }

    var sameNameItem = items.find(function(item) { return item.name === targetName; });
    if (sameNameItem) {
        // upload new version of sameNameItem.id
    } else {
        // upload new file
    }
});
```

One other option is to make a Preflight Check request to see if the upload would succeed and then decide what to do based on the response:

```js
client.files.preflightUploadFile(folderID, {name: 'file.csv', size: sizeOfCSVFile}, null, function(err, data) {
    if (err) {

        if (err.statusCode === 409 && err.response.body.code === 'item_name_in_use') {
            // Upload a new version of file with ID err.response.body.context_info.conflicts.id
        } else {
            // handle error
        }
        return;
    }

    // Upload the file as a new file
});
```

Personally, I would prefer the second approach; since it will work even if the folder has more than 1000 items in it.  However, if you know that these folders will never have that many items in them, the first approach looks a bit simpler and should work just fine.

**Comment by montrealist** [comment]
Got it. The `preflightUploadFile` looks more attractive, will try it out. Big thank you for the guidance and the timely response!
