### ISSUE TITLE
How to refresh token when exist token(developer token) is expired

### ISSUE THREAD

**Issue by maruthi-menlo** [box/box-node-sdk#112]
Please help me to get refresh token, while i am accessing with expired token(developer token).

**Comment by mattwiller** [comment]
Hi @maruthi-menlo — the developer token is meant for testing out the API, and is not able to be refreshed.  If you need another developer token, you can just go to the [Dev Console](https://app.box.com/developers/services) and generate another one.  This will allow you to make API calls for another hour until it expires, at which point you can just go get another one.

If you want a full access token/refresh token pair in order to refresh the tokens automatically, you will need to go through the [OAuth2 flow](https://docs.box.com/docs/oauth-20).  Here's some help for how you might do that:

0. Either implement a TokenStore, or download the one from `examples/token-store.js` in this repository.
1. First, you can call `sdk.getAuthorizeURL({response_type: 'code'})` to get the URL that a user should be redirected to to log in.
2. Visit that URL in a web browser and enter your login information.
3. You will be redirected to whatever `redirect_url` you set up in your app.  In that URL there should be a `code` query string parameter.  Quickly copy the value of that parameter and call the API to get the access and refresh tokens like this:

```js
var TokenStore = require('./path/to/token-store');
sdk.getTokensAuthorizationCodeGrant(code, null, function(err, tokenInfo) {
    
    if (err) {
        console.log('Error exchanging auth code!', err);
        return;
    }

    console.log('Got token info!', tokenInfo);
    var tokenStore = new TokenStore('test');
    var client = sdk.getPersistentClient(tokenInfo, tokenStore);

    // Use the client to make API calls!
});
```

If you're doing these steps by hand, you will need to do this quickly, since the authorization code expires in 60 seconds.
