### ISSUE TITLE
Can not see the files on the Main Box Web Interface after uploaded

### ISSUE THREAD

**Issue by noobiehacker** [box/box-node-sdk#113]
Hello all

I am just running the 'app-auth' sample app and uploaded a file onto box.
However, when I go back to the original box web interface, I couldn't see the file and can't search for it anywhere.

However, in the node js app, its able to find it and return the image.  

I am very confused as to where is the file actually stored, please help!! ><

**Comment by mattwiller** [comment]
@noobiehacker The App Auth sample creates and works with [App Users](https://docs.box.com/docs/app-users), which are owned by your application and do not have actual Box logins (i.e. for the Box web application).  This auth model is used for apps that will provision and manage their own users' accounts separate from Box.

If you want to interact with standard Box user accounts, you will need to use the [OAuth2](https://docs.box.com/docs/oauth-20) flow to get access and refresh tokens for that user, which is a little more involved.  Here's some help for how you might do that:

0. Either implement a TokenStore, or download the one from `examples/token-store.js` in this repository.
1. First, you can call `sdk.getAuthorizeURL({response_type: 'code'})` to get the URL that a user should be redirected to to log in.
2. Visit that URL in a web browser and enter your login information.
3. You will be redirected to whatever `redirect_url` you set up in your app. In that URL there should be a `code` query string parameter. Quickly copy the value of that parameter and call the API to get the access and refresh tokens like this:

```js
var TokenStore = require('./path/to/token-store');
sdk.getTokensAuthorizationCodeGrant(code, null, function(err, tokenInfo) {
    
    if (err) {
        console.log('Error exchanging auth code!', err);
        return;
    }

    console.log('Got token info!', tokenInfo);
    var tokenStore = new TokenStore('test');
    var client = sdk.getPersistentClient(tokenInfo, tokenStore);

    // Use the client to make API calls!
});
```

If you're doing these steps by hand, you will need to do this quickly, since the authorization code expires in 60 seconds.
