### ISSUE TITLE
JWT doesnt work with nodeJS SDK for Box

### ISSUE THREAD

**Issue by ksleima** [box/box-node-sdk#150]
JWT doesnt work with nodeJS SDK for Box- token is always expried even when passign ASSERTION exp and iat are valid. this was supposedly fixed in 1.4.0 but is definitrly not.

**Comment by mattwiller** [comment]
Hi @ksleima — thanks for reaching out!  The `exp` claim is generated from your host's clock, which may not be synchronized with Box's servers.  We implemented some retry logic in v1.4.0 to try and work around unsynchronized clocks, but it's not foolproof.  Generally, the best way to fix this issue is to ensure that the machine your application is running on uses NTP to synchronize its clock, but I can help you investigate what's going on.  If you can, you can email me your API key (NOT your API secret), the contents of `error.response` for the errors you're seeing, and the time period where you're seeing these errors, and I'll take a look.  My email address is in my profile.

**Comment by ksleima** [comment]
@mattwiller 
I just emailed you. Thanks for your help

**Comment by mattwiller** [comment]
To close the loop here, @ksleima and I found two issues while debugging in a separate email thread:

1. In app auth config, setting `expirationTime` to longer that 60 seconds is not supported by the Box API, and will result in the auth request failing.
2. An issue with the app's public key that was fixed by generating a new keypair in the Box Developer Console.

To address the first problem, I'm changing the default value of `expirationTime` and adding better validation in #151
