### ISSUE TITLE
Create Typescript definitions

### ISSUE THREAD

**Issue by smithdalec** [box/box-node-sdk#170]
My organization is using the Box Node SDK in a Typescript project, and we've been creating our own type definitions for all the pieces of the SDK that we use, but would benefit from a types library contributed to by Box (and any other contributors of the SDK) so we don't have to build types every time we start using a new feature of the Box API.

Are there any plans for Box to build some Typescript definitions for this SDK?
If not, I can submit a PR to either this repo or DefinitelyTyped with some of the types I've already created. Any preference there?

**Comment by mattwiller** [comment]
Hi @smithdalec — Typescript definitions are definitely something we've thought about adding, potentially by converting the SDK itself over to Typescript.  We're not sure where this falls on our backlog, though, so if you have something already working for your project, it would be great to see to give us somewhere to start from so we can decide how we want to go about providing types.  Would you mind making a PR here with what you've created?

**Comment by kachkaev** [comment]
Hey @mattwiller and other Box members 😉 

What are your current views on switching to TS in future? Just curious.

**Comment by mattwiller** [comment]
Hi @kachkaev — we're definitely interested in moving the SDK over to TypeScript!  There are some other major refactors/improvements we're looking into for the Node SDK in the medium term, and we would probably roll the transition to TypeScript in with those changes.

**Comment by jgoldhammer** [comment]
Hi @mattwiller. Any progress here or ETA? Thanks, Jens

**Comment by mattwiller** [comment]
@jgoldhammer There's no update as of now, but this continues to be something we would like to support (we just haven't found the time to work on it yet!)

**Comment by mattwiller** [comment]
@tharun208 Ideally we would want to provide proper typings, especially to help out with the data that gets returned by the API calls.  At the very least, this is something we're strongly looking at for the next major version of the SDK.

**Comment by tharun208** [comment]
Thanks @mattwiller , will look into it

**Comment by mattwiller** [comment]
@tharun208 I think for now putting it in @types/box-node-sdk would be the best option

**Comment by bishtawi** [comment]
Any progress @mattwiller ?

**Comment by carycheng** [comment]
Hey @bishtawi,

Currently this is not on our roadmap but we understand and hear the desire from the community to have this. We will keep you updated if there is a change on this front but unfortunately converting the Box Node SDK to include TypeScript definitions is not currently planned as of yet.

**Comment by theodore-koch** [comment]
I created a pull request to begin adding type defs for this sdk if anyone else wants to contribute to it

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41813

**Comment by sgalizia** [comment]
I would like to bump this to increase visibility for Box. We are using this in a TS project very heavily and we would greatly benefit from types. Pretty sure it would be possible to create a type file without having to convert the whole sdk over. Would love to hear from you all as to when this will finally be deemed important enough to put on the roadmap.

**Comment by sgalizia** [comment]
> 
> 
> I created a pull request to begin adding type defs for this sdk if anyone else wants to contribute to it
> 
> [DefinitelyTyped/DefinitelyTyped#41813](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41813)

Your PR had issues and was closed by the maintaining bot. Thank you for at least trying to get that going though!

**Comment by dawinter** [comment]
Any update for providing type definition for Box SDK?

**Comment by Yossitrx** [comment]
Hey, any updates providing types for Box node SDK?

**Comment by ThomasFlorelli** [comment]
Hello, I have 2 statements and a few questions.

### Statement 1

The only way to properly type my Box-related code right now is to read through every file, find out whether or not what I'm looking for is typed, and import the specific file I need like so:

```typescript
import BoxNodeSDK from "box-node-sdk/lib/box-node-sdk";
import BoxClient from "box-node-sdk/lib/box-client";
```

### Statement 2

Even with that trick, there are some important concepts that don't seem to be typed like the composition of a user or folder. I have noticed the code contains a majority of `any` for types.

### Questions

- Is there a simpler way I might be missing?
- If not, due to this issue being closed, should I consider that we reached the final state of typing on this repository?
- Is the current typing complete enough for someone to create a PR on DefinitelyTyped?
- If not, should this issue be reopened?


Thank you for reading

**Comment by mhagmajer** [comment]
Hi @ThomasFlorelli. We've shipped initial version of our TypeScript definition and closed this ticket so that we could focus on more detailed TypeScript issues. There is an ongoing effort to replace the remaining `any` annotation with the specific types. Would you mind creating a separate issue with your questions, ideally including the code you're trying to type? Thanks!
