### ISSUE TITLE
Issue using chunked uploader

### ISSUE THREAD

**Issue by patriciali** [box/box-node-sdk#207]
I'm trying to use the chunked upload API (https://developer.box.com/reference#chunked-upload) via the Box Node SDK (https://github.com/box/box-node-sdk/blob/master/docs/files.md#chunked-upload) to upload large files. I'm using request (https://www.npmjs.com/package/request#streaming) to get an http.IncomingMessage (https://nodejs.org/api/http.html#http_class_http_incomingmessage), which implements the ReadableStream interface, then passing it as an argument to the Box Node client, like so:

```
request.get(url).on('response', readableStream => { 
    this._boxClient.getChunkedUploaderAsync('0', filesize, filename, readableStream, null, (err, uploader) => { 
        if (err) {...}

        uploader.on('error', err => {...}); 
        uploader.on('uploadComplete', file => {...});

        uploader.on('uploaded', data => { 
            h.console.logRed('data of the uploaded chunk', data); 
        }); 
        uploader.on('chunkUploaded', data => { 
            h.console.logRed('data of the uploaded chunk', data); 
        }); 
        uploader.on('chunkError', err => { 
            h.console.logRed('chunkError', err); 
        });

        uploader.start(); 
    }); 
});
```

However, when I try to upload a ~50mb PDF, I find that the first 5 chunks upload successfully, but the last fails with a 400 (at least judging by the 'offset' field). I couldn't find a helpful error message, but here's the logging from the above code: https://www.dropbox.com/s/s1pgzm59wmeuykl/log.txt?dl=0

Here is the file I was using to test: https://www.dropbox.com/s/w7kxrdv31tliblb/Artificial%20Intelligence%20A%20Modern%20Approach%203e%20%282009%29.pdf?dl=0

**Comment by mattwiller** [comment]
Hi @patriciali — based on the logs you sent it looks like the error is due to an invalid part size.  It looks like this is probably due to the `filesize` specified in `this._boxClient.getChunkedUploaderAsync()` being incorrect — you told the API to expect that many bytes but the stream ran out of bytes before that point.  The API expects each chunk uploaded to have uniform size except for the last one, which should cover the range of bytes from the end of the last chunk to the end of the file.  In this case, if the stream did not have as many bytes as specified, that "last" chunk won't cover to he end of the file, but also won't be the same size the the other chunks, so the API will throw an error.  Can you please double-check the file size and let me know if that's the issue?

**Comment by patriciali** [comment]
Hi @mattwiller, thanks for the quick response.

The value we're passing into `getChunkedUploaderAsync` looks correct. "Get info" on my Mac says 49,904,616 bytes (see https://www.dropbox.com/s/kd0kwj1ibp7ov4b/ai-size.png?dl=0), which is the value we're passing.

The error log says `_bytesDispatched: 7457628` for the last chunk, so I tried passing in 5 * 8388608 + 7457628 = 49400668. This also failed, but with a 416 instead of a 400: https://www.dropbox.com/s/qre0lexcmy7jrb3/log416.txt?dl=0.

If the filesize value we're using is incorrect, how do we get the "correct" one?

**Comment by mattwiller** [comment]
Hmm, there seems to be something strange going on then — perhaps the stream isn't correctly providing the bytes or the file size from over the network is somehow different than what you have on disk?  I'm not totally sure what the `_bytesDispatched` property means on a net stream, but based on the logs you sent it looks like the stream was just a little off on how much data it provided.  The request that caused the 400 error had the header `Content-Range: bytes 41943040-49574358/49904616`, which means the last chunk the stream provided was 7,631,318 bytes, rather than either the full chunk size of 8,388,608 bytes or the 7,961,576 bytes necessary to reach to full file size that you specified.

I have a couple ideas for how we might troubleshoot this:
1. If you specify a file size of `49574358` — the number of bytes the stream was actually able to provide — does the file upload successfully?
2. If you check the contents of the stream manually via something like `request.get(url).on('response', stream => stream.on('data', data => console.log(data.toString())));`, does that looks like the full file that you're expecting?

**Comment by patriciali** [comment]
1. Nope :( Although strangely enough it looks like it's using chunk sizes twice as big (`16777216` instead of `8388608` like before). Log: https://www.dropbox.com/s/83leuftnv2wfrnn/log49574358.txt?dl=0
2. It looks like it. I didn't compare the entire string, but the first dozen or so and last dozen bytes match.

For what it's worth, if I first download the entire file into memory (using the same lib) and pass it as a Buffer to the factory for the chunked uploader, it seems to work fine, but we're trying to avoid downloading large files into memory...

**Comment by mattwiller** [comment]
Hmm, okay then — thanks for testing that out for me.  Our company firewall blocks Dropbox, so it's hard for me to get to the logs and sample file that you've posted.  Would you mind emailing them to me at mwiller@box.com — I'll try on my computer to see if I can reproduce the problem and debug it in my environment.

**Comment by patriciali** [comment]
Done

**Comment by mattwiller** [comment]
Thank you!  I'll start investigating today and let you know what I find out.

**Comment by mattwiller** [comment]
@patriciali It looks like the issue is a bad interaction with the way `request` handles the stream internally — it looks like `request` places the stream into flowing mode by default sometime after the "response" event is fired.  This causes inconsistency in trying to read the stream manually later after the upload session is created since some bytes may have already been read from the stream.  This appears to only be an issue with streams from `request`; streams from e.g. `fs.createReadStream()` or manually using the Node HTTP library to get an IncomingMessage directly don't have this problem because nothing places them into flowing mode.  I suspect this is due to `request` providing both a stream interface and a callback interface via the same function call — in order to pass the full response to a callback it would need to start reading data from the underlying IncomingMessage at some point.

The SDK's chunked uploader already tries to handle this by automatically pausing any stream passed into the ChunkedUploader constructor.  However, this only works if you pause the stream **immediately** before `request` tries to put it into flowing mode.  Since creating the upload session is asynchronous, `request` has a chance to put the stream into flowing mode before the SDK pauses the stream.  I have a change that should fix this in the SDK (by pausing the stream **before** creating the upload session, but you can work around this right now until we get the fix released by manually pausing the stream yourself:

```js
request.get(url).on('response', readableStream => { 
    readableStream.pause(); // PAUSE THE STREAM RIGHT AWAY!
    this._boxClient.getChunkedUploaderAsync('0', filesize, filename, readableStream, null, (err, uploader) => { 
        if (err) {...}

        uploader.on('error', err => {...}); 
        uploader.on('uploadComplete', file => {...});

        uploader.on('uploaded', data => { 
            h.console.logRed('data of the uploaded chunk', data); 
        }); 
        uploader.on('chunkUploaded', data => { 
            h.console.logRed('data of the uploaded chunk', data); 
        }); 
        uploader.on('chunkError', err => { 
            h.console.logRed('chunkError', err); 
        });

        uploader.start(); 
    }); 
});
```

Please let me know if the workaround helps your situation, or if you have any other questions!  I'll keep this ticket open until we land a fix in the SDK that corrects this issue.

**Comment by patriciali** [comment]
@mattwiller that did the trick - thanks for your help investigating!
