### ISSUE TITLE
How to generate a unique access token?

### ISSUE THREAD

**Issue by ovvn** [box/box-node-sdk#208]
I need to generate a unique access token for each user that opens up a preview on the client side.

Currently on the server side of my node project I obtain an access token as follows:
```coffeescript  
getAccessToken: (req, res) ->
    enterpriseClient = sdk.getAppAuthClient 'enterprise', enterpriseID
    enterpriseClient._session.getAccessToken()
      .then (token) ->
        res.json {token}
```
Problem is when 100 users open up a preview simultaneously they get the same `accessToken` which breaks the `limit of 10 API calls per second per user`. Is there a way to generate a unique access token each time or other solution for the issue using the box-node-sdk?

**Comment by mattwiller** [comment]
Hey @ovvn — if you have users for your application that you want to "shadow" on Box, so that each of your users has their own corresponding Box account that your application manages, you should create App Users for them and maintain some sort of mapping between your users and their App User accounts.  For example, our [sample app](https://github.com/box/box-node-sdk/blob/master/examples/app-auth/index.js) does something like this — it uses the user's email address as their name in Box, and uses that field to look up the correct user.  If you have an App User account set up for your user, you can do `sdk.getAppAuthClient 'user', userID` to get a unique client (and access token) per user.

**Comment by ovvn** [comment]
Thank you very much for the approach. It does generates unique tokens but unfortunately the app users' access tokens don't work for a content preview. First I created some app users as follows:
```coffeescript
 boxEnterpriseClient.enterprise.addAppUser 'userName', {}, ->
```
Also tried the way it's implemented in your [sample](https://github.com/box/box-node-sdk/blob/master/examples/app-auth/index.js#L139-L142) - worked great.
So I obtained new app users in the format:
```json
    {
      "type": "user",
      "id": "316384xxxx",
      "name": "xxx",
      "login": "AppUser_xxxxxx_xxxxqCUq4L@boxdevedition.com",
      "created_at": "2018-01-13T05:31:37-08:00",
      "modified_at": "2018-01-13T05:31:37-08:00",
      "language": "en",
      "timezone": "America/Los_Angeles",
      "space_amount": 10737418240,
      "space_used": 0,
      "max_upload_size": 5368709120,
      "status": "active",
      "job_title": "",
      "phone": "",
      "address": "",
      "avatar_url": "https://decisionmapper.app.box.com/api/avatar/large/316384xxxx"
    }
```
Then tried to get an access token for the newly created app user as follows:
```coffeescript
user = sdk.getAppAuthClient 'user', '316384xxxx'
user._session.getAccessToken()
   .then (token) ->
      res.json {token}
```
But when I try to use the access token in the preview, it doesn't show any preview saying "We're sorry, the preview didn't load. Please refresh the page."

If I generate token as before using the enterprise user, everything's fine.

**Comment by mattwiller** [comment]
@ovvn Are you sure the newly-created app user has access to the files your want to preview?  Since the app user is its own account, any content you want it to be able to access will need to be collaborated with it — it does not automatically get access to the service account's files.

**Comment by ovvn** [comment]
@mattwiller yes I also think there's something wrong with permissions, but couldn't find how to fix it. On the box web site I can choose an app user and select folders this user can access, but it doesn't show me a folder with all files that were uploaded by the app. Initially I created an app and uploaded a bunch of files there to the 'root' (id=0) folder. Now I can't find a way how to "share" this destination folder with my newly created app users. I thought maybe there's a way to move all those files to another folder which is visible on the box dashboard and can be shared with all app users.

**Comment by mattwiller** [comment]
@ovvn If you have a non-root folder in the service account (the one you get with `sdk. getAppAuthClient 'enterprise' ...`), you can [add a collaboration onto that folder](https://github.com/box/box-node-sdk/blob/master/docs/collaborations.md#add-a-collaboration) with your `enterpriseClient` in order to grant the app user account access to the folder.

**Comment by ovvn** [comment]
@mattwiller it makes sense and I created an empty non-root folder in the service account, but how can I move all files in the root folder to the non-root folder?

**Comment by mattwiller** [comment]
Hey @ovvn — please see the documentation for [getting the items in a folder](https://github.com/box/box-node-sdk/blob/master/docs/folders.md#get-a-folders-items) and [moving a file](https://github.com/box/box-node-sdk/blob/master/docs/files.md#move-a-file) — you can get the items in the service account's root folder (which has ID `'0'`) and move them into the new folder you created.  Then you can collaborate that folder with each app user you create, which will give them access to all the files within.

**Comment by ovvn** [comment]
hi @mattwiller, really appreciate your help. it worked.
