### ISSUE TITLE
Rate limiting: is `Retry-After` header respected?

### ISSUE THREAD

**Issue by patriciali** [box/box-node-sdk#213]
The [docs](https://developer.box.com/reference#rate-limiting) claim that Box API will send a `Retry-After` header with 429 responses indicating how much time we should wait before making the next request. But that header doesn't seem to be respected in the Node SDK. I see a reference in [files.commitUploadSession](https://github.com/box/box-node-sdk/blob/7146ece42bfb27f251eaad5c582a78f31e1572a4/lib/managers/files.js#L1141), but the [default retryIntervalMS](https://github.com/box/box-node-sdk/blob/6f9709121181b6a289e4d97907c5e54d409a8162/lib/util/config.js#L58) has a hard-coded default of 2000ms (and I guess you can pass in a different value). Are there plans to respect the `Retry-After` header?

**Comment by mattwiller** [comment]
Hi @patriciali — there's actually a discussion about this exact issue going on over at the [Box Java SDK](https://github.com/box/box-java-sdk/issues/438)!  We're planning to implement exponential backoff with randomized jitter in the Node SDK, and do not plan to respect the Retry-After header in error scenarios (e.g. the 429 Too Many Requests response) since it does not give enough information for clients to properly reduce load.  In this case, the recommended practice is to have clients back off exponentially rather than by a fixed amount, which means we'll need to ignore the Retry-After header.

**Comment by patriciali** [comment]
Hah, gotcha. How would you recommend we cobble on an exponential backoff in the meantime? (Or is that recommended?) Also, just for reference, do you have an estimate of when the backoff logic will be added to the Node SDK?

**Comment by mattwiller** [comment]
You shouldn't need to implement exponential backoff yourself — if the SDK is working fine for you today, it's not worth the effort.  Adding better retry logic to the SDK is on our roadmap for the next three months, so it'll probably land by the end of March.

**Comment by patriciali** [comment]
I see. I'm asking because earlier this week we saw a spike of 429s from Box. We're trying to figure out with Box support whether it was due to hitting our monthly storage/API request limits, or whether we were sending too many requests within a shorter window of time, but given that the [docs](https://developer.box.com/reference#rate-limiting) say

> The first is a limit of 10 API calls per second per user. The second limit is 4 uploads per second per user.

I'm guessing it's the latter. We're working on reducing the volume of requests that we send to Box, but I'm wondering if better retry logic would also help.

**Comment by mattwiller** [comment]
You're correct — a 429 response would indicate that your application has made too many calls in a short period of time.  Better retry logic would probably help your app recover from hitting the rate limit (which is why we're prioritizing that work this quarter!), but you may want to to try ensure within your application that you don't hit the rate limit in the first place.  If you can share, what sort of calls is your app making that are causing you to hit the rate limit?

**Comment by patriciali** [comment]
We're using Box to power thumbnail generation and document previews within our product. For each file a user uploads, we do the following:
1. Upload the file to Box (chunked upload if it's > 20mb)
2. Use getRepresentationInfo to get the URL to trigger thumbnail processing
3. Send  GET to that URL to trigger thumbnail processing
4. Poll getRepresentationInfo every 5 seconds until the thumbnail status is 'success'
5. Download the thumbnail

So we're making at least 5 API requests per file (and possibly more, if the polling takes a while). I imagine we're hitting the rate limit because we have many users who are all uploading files to our service, which is resulting in a bunch of concurrent API calls to Box from our servers.

I think our plan will be to restrict the number of document uploads/previews for free users, and deal with hitting the rate limit with better retry logic (either when it's shipped with the Node SDK, or our own logic), although now I see that the retry logic is more of a band-aid, and reducing volume is the real issue.

**Comment by mattwiller** [comment]
Since rate limits are defined per Box user, the way your app is set up may have an impact here.  Can you share how you're doing authentication?  There are four options for Box API authentication:

1. __Traditional 3-legged OAuth2__: If your users are already Box users and you want to integrate with their existing Box accounts, you can have them authorize your app and get a rate limit unique to each user by making calls on their behalf.
2. __JWT auth with Service Account__: It's pretty straightforward to get set up with a single service account authorized via JWT, but this has a big impact on rate limits because you only have one user that you're making calls from.
3. __JWT auth with App Users__: Your application can [create multiple app users][createAppUser], either with a 1:1 mapping to your application's actual users, or as a simple pool of users to make requests through.  This gives you additional flexibility in making requests since you're not constrained by a single user's rate limits.
4. __App Token (Transactional) auth__: If your app is using [Box View][boxView], you just have a long-lived access token and you're not doing any sort of complicated auth.  Your rate limits will be related to the pricing and single-user rate limits.

Do you know which type of auth you're currently using?  If you're doing Option 2, you may want to switch to Option 3 (or Option 1 if all your users are already Box Users).

[createAppUser]: https://github.com/box/box-node-sdk/blob/master/docs/enterprise.md#add-new-app-user
[boxView]: https://developer.box.com/v2.0/docs/box-view

**Comment by patriciali** [comment]
We're doing 2. 3 looks promising. A couple questions:
1. We had to manually increase the storage limit on our service account from the default 10gb to "unlimited". I saw [this](https://developer.box.com/v2.0/reference#update-a-users-information) API endpoint, but couldn't figure out what the user_id of the service account was, and when I wrote into support the guy told me to do it manually with the "bulk edit" tool. Is it possible to increase storage limits to "unlimited" on app user accounts programmatically, or do we have to do it manually beforehand?
2. Would we have to renegotiate our contract with Box for an increased number of seats? Looks like we currently only have 1 (see screenshot [here](https://airtable.com/shrvZMPXKU4FGGROE/tblIHvzL1XgKJKU9L/viw3GneamX144kwTs/rec2BPwyrgzDXoD24)).

**Comment by mattwiller** [comment]
1. According to the [API Reference docs](https://developer.box.com/v2.0/reference#update-a-users-information) you _should_ be able to update the App User's storage limit to unlimited by doing something like `client.users.update(appUserID, { space_amount: -1 })`.  You can get the ID for the app user from the returned object when you create it.

2. I'm not an expert on the pricing or contracts for developers, but the {Box Platform pricing page](https://www.box.com/pricing/platform) has pricing tiers for the number of users that are active for your enterprise in a given month.  I don't want to give you a wrong or misleading answer here, so I'll send you the email of someone at Box who you can talk to about exactly what your use case is and how that might affect your contract and pricing.

**Comment by patriciali** [comment]
Got it. I guess we'll need to discuss internally and decide what to do, so I'll just close this ticket, since my original question was answered anyway. Thanks!

**Comment by dcods22** [comment]
@mattwiller I was wondering if the 429 backoff was ever implemented into the SDK? We consistently run into this issue and are running the latest version of the SDK.  I was not sure if there was something we needed to configure or do differently

**Comment by mattwiller** [comment]
@dcods22 Yes, all versions of the Node SDK from v1.13.0 onwards use exponential backoff for retries, up to the configured maximum number of retries (default 5).  If you're still running into rate limit issues, you can try to increase the base retry time or increase the maximum number of retries.  Both of these values can be configured like this:

```js
sdk.configure({
    retryIntervalMS: 4000, // increase the base retry delay from 2s (default) to 4s
    numMaxRetries: 10, // increase the number of retries from 5 (default) to 10
});
```

In the latest version of the SDK, you can also specify a custom retry strategy like so:

```js
sdk.configure({
    retryStrategy: function(retryInfo) {
        return retryInfo.numRetryAttempts * 5000; // linear retry, 5s * attempts
    }
});
```
