### ISSUE TITLE
Upload binary file directly to Box

### ISSUE THREAD

**Issue by ORESoftware** [box/box-node-sdk#250]
I have this Angular handler, which can upload an image to Artificatory/JFrog:

```js
      createNewAcqImage: function (options) {

        let file = options.file;

        return $http({
          method: 'POST',
          url: '/proxy/image',
          data: file,
          headers: {
            'Content-Type': 'image/jpeg',
          }
        });

      },
```

this request gets sent to our server, which forwards the request to JFrog / Artifactory:

```js
router.post('/proxy/image', function (req, res, next) {
  
  const filename = uuid.v4();
  const auth = getAuthStr();
  
  const proxy = http.request({
      method: 'PUT',
      hostname: 'box.nabisco.com',
      path: `/storage/${filename}`,
      headers: {
        'Authorization': auth,
      }
    },
    function (resp) {
      resp.pipe(res);
    });
  
  req.pipe(proxy);

});
```

my question is - is there a way to upload a file directly to box without using form-data? It would be nice to stream all the way to box, instead of buffering it on one of our servers. If we can send it directly from the browser, that'd be nice too.

**Comment by mattwiller** [comment]
@ORESoftware I'm not quite sure what you're asking here — could you elaborate a bit about what you're trying to do?  The SDK supports [uploading files from a Stream](https://github.com/box/box-node-sdk/blob/master/docs/files.md#upload-a-file), which does use `form-data` under the hood since this type of upload requires a multi-part form in the API.  If the files you're uploading are 20MB or larger, you can also use [Chunked Upload with a stream](https://github.com/box/box-node-sdk/blob/master/docs/files.md#automatic-uploader).  If you want to upload files from the browser, we have a [Content Uploader UI Element](https://developer.box.com/docs/box-content-uploader) that you can drop into your application, or you could manually use the Node SDK to [create a token with only item_upload scope](https://github.com/box/box-node-sdk/blob/master/docs/authentication.md#token-exchange) and pass that down to the browser, where your client-side code could make the upload API call itself.

**Comment by ORESoftware** [comment]
@mattwiller thanks for responding - we are actually trying to upload just one file and we want to avoid form-data / multi-part data.

As you can see in the code above, the data is just included in the request body and is not in the form of attachments/parts.

So what it would look like from the Box point of view: Box would have an endpoint that expects binary data, but not form-data, if that makes sense. TBH I am not an expert on how form-data differs from data that's just part of the request body.

**Comment by mattwiller** [comment]
@ORESoftware Can you explain a bit more why you don't want the Box API to use a multipart form body for upload?  If you're using the SDK, you should be able to pass a stream with just the plain binary content to the `uploadFile()` method and the SDK will construct the multipart form for you — you shouldn't need to worry about it.  Your own application should not need to accept a multipart form in order for this to work.  Are you running into a specific problem around that?

**Comment by ORESoftware** [comment]
I just added a line above, I think the automatic uploader will work for us:
https://github.com/box/box-node-sdk/blob/master/docs/files.md#automatic-uploader

does that really use multipart data under the hood? It shouldn't have to.

**Comment by mattwiller** [comment]
The Chunked Upload functionality does not use multipart data under the hood, but note that it is only available for files larger than 20 MB.  In either case, though, your choice of upload method to Box should not require any change in your application.  Both methods accept a stream of just the binary content of the file you're trying to upload.  The multipart form stuff is just an implementation of the API call to Box, not something your application should need to implement.  Did you try using `uploadFile()` and see an error?  I want to make sure the SDK correctly supports this kind of use case.

**Comment by ORESoftware** [comment]
@mattwiller honestly asking for a coworker who was struggling to get it to work, but I don't have a complete handle on the problems he is facing - he's somewhat of nodejs newb so

**Comment by mattwiller** [comment]
No problem — let me know what you see!  If there's anything we can do to help, please let us know.

**Comment by ORESoftware** [comment]
One question I have tho now that I think about it - why the 20mb threshold? Seems arbitrary? We may wan to use that functionality even with a file that's 1mb, or 5mb..

**Comment by mattwiller** [comment]
That's a limitation set by the API, which I believe is because it just doesn't make sense to use Chunked Upload on files that small.  The Chunked Upload functionality is intended to improve the reliability of large file uploads by allowing you to upload parts of the file independently, so that if one part fails you don't have to retry the whole upload.  The size of each chunk is determined by the API, and was set at 8 MB the last time I checked.  So, for a 5 MB file, you would be uploading the whole file in one API call either way.  In that case, using Chunked Upload doesn't really give you any advantage and increases the complexity of the operation since you need to do extra stuff like create an upload session and keep track of part records and a SHA1 hash and then commit the upload session.  It's simpler and just as reliable to just upload a small file the "standard" way and retry on failure.
