### ISSUE TITLE
Issue with Multiple File Upload with sdk

### ISSUE THREAD

**Issue by nikhilmk0704** [box/box-node-sdk#397]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I have built application in Angular 2(version 7.2.0) as front end and Node JS as back end for uploading files to Box. It is a multi file upload with drag and drop feature, but when i try to upload more than 10 files at a time it uploads 10 files and the rest is not getting uploaded. It works seamlessly for less than 10 files. It seems it related with the API call limit 10 APIs per second per user. I am calling the box "uploadFile" API in a loop from angular front end. 

In the application i am using the JWT Configuration and the client connection is a enterprise connection. The application sdk version as follows.

### Versions Used
Node SDK: ^1.29.0
Node.js: 8.11.1

### Error Message, Including Stack Trace
There is no response from the Box Server after 10 API calls, and the first 10 files is uploading properly. 

Help required to overcome the API limit with box using a JWT enterprise connection

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @nikhilmk0704,

It seems you are indeed running into the call limit. One way you can circumvent this issue is with the use of multiple [application users](https://developer.box.com/reference#create-app-user) to make the upload calls. This will spread out the number of calls coming from one source and can help solve your call limit issues.

You will need to:

1. Create App Users to use in the upload calls. As seen [here](https://github.com/box/box-node-sdk/blob/master/examples/app-auth/index.js#L133). The most important part to pay attention to is the request body for this call. App user takes two fields: `login` and `is_platform_access_only` set to `true`.

2. Then after you have a pool of application users you will be using a mechanism or your choice to schedule which user makes which number of upload call(round robin as an example).

3. You will use this [as-user header](https://github.com/box/box-node-sdk/blob/master/docs/authentication.md#as-user) to make the upload on behalf of the app user you created in the previous step. Now you can make multiple concurrent api calls as long as each app user does not exceed the call limit.

Please let us know if you run into any issues in setting this up.

Much appreciated!

**Comment by nikhilmk0704** [comment]
Hey carycheng,
Thank you so much for the workaround. In the 3rd Step when i am making the created user as as-user header then trying to do upload it gives a 403 forbidden error in the api response

**Comment by carycheng** [comment]
@nikhilmk0704, the 403 Forbidden error you are seeing can be many things unfortunately - Incorrect scopes on token, app not authorized correctly, app failing certain permission checks.

To help us better diagnose - can you please send over your API response, API Key(which is the client ID), as well as your request ID(in the API response) to ccheng@box.com(as the information is sensitive and should not be posted here).

Once we have that we can look through our logs, find the specific issue and resolve this. Thank you for your patience as we look into this.

Much appreciated!

**Comment by carycheng** [comment]
Hey Nikhil,

It looks like you have the correct scopes. Could you try reauthorizing your application in your admin console? It seems like you may have increased the scope of you app sometime after you initial app authorization. In order for the updated scopes to take effect you will need to reauthorize your application as well. 

This article may be helpful: https://community.box.com/t5/How-to-Guides-for-Admins/Enabling-Custom-Built-Applications/ta-p/2188

If you are still seeing the issue afterwards please provide us your:

- Enterprise ID
- Access token type you are passing into the header - meaning which authentication type did you use to(grant_type) to generate your access token?

All this will be very helpful in helping us debug.

**Comment by PJSimon** [comment]
Hi @nikhilmk0704 , I'm closing this old issue, but if you still need help, please just re-open it!  Thanks!
