### ISSUE TITLE
Groups/Memberships feature request

### ISSUE THREAD

**Issue by jonathanprl** [box/box-node-sdk#8]
Will groups and memberships be added at some point?

Also, is there a reason that you guys use polling over websockets for the real-time events? Slightly off-topic but intrigued to know.

**Comment by aamave** [comment]
Yes, groups and memberships will be supported. We are scoping the work for that over the next few weeks and then should have a better estiamte on timing.
As for events, I'll leave that to one of the authors.

**Comment by mattwiller** [comment]
For the SDK, we use polling instead of websockets because the Box API is RESTful and doesn't support websockets at this time.  That said, I believe that the SDK's event stream abstraction should act the same as if it were fed by a websocket; if there's anything that you think could be improved there we'd be happy to take a look at it.  That said, if you want more of a "push" solution from the API itself today, we have a [new version of Webhooks](https://docs.box.com/docs/getting-started-with-webhooks-v2) that's current in beta — feedback welcome!

Also, we'll be looking into adding Groups and Membership endpoints to the SDK ourselves in the future, but you are of course more than welcome to submit a pull request of your own if you're at all interested in trying to add them yourself — I'd be more than happy to work with you on getting it reviewed and merged.

**Comment by mattwiller** [comment]
This functionality was added in #69

**Comment by mattwiller** [comment]
@jonathanprl The latest version of the SDK (v.1.2.0) adds support for Groups/Memberships operations — please give it a try and let me know if you encounter any difficulties!
